version: '2'

services:
  dcc-dashboard-service:
    environment:
      APACHE_PATH: "${apache_path}"
      ES_SERVICE: "${es_service}"
      DATABASE_URL: "${database_url}"
      L_POSTGRES_USER: "${login_user}"
      L_POSTGRES_PASSWORD: "${login_password}"
      L_POSTGRES_DB: "${login_db}"
      POSTGRES_USER: "${postgres_user}"
      POSTGRES_PASSWORD: "${postgres_password}"
      POSTGRES_DB: "${postgres_db}"
      AWS_PROFILE: "${aws_profile}"
      AWS_ACCESS_KEY_ID: "${aws_access_key_id}"
      AWS_SECRET_ACCESS_KEY: "${aws_secret_access_key}"
      B_POSTGRES_PASSWORD: "${billing_password}"
      B_POSTGRES_USER: "${billing_user}"
      B_POSTGRES_DB: "${billing_db}"
      FLASK_APP: "/app/mapi.py"
      DCC_DASHBOARD_HOST: "${dcc_dashboard_host}"
      SECRET_KEY: "${secret_key}"
    image: quay.io/ucsc_cgl/dashboard-service:1.0.9
    volumes:
      - ~/dcc-dashboard-service/logs:/app/log
    #build: dcc-dashboard-service
    ports:
      - "80"
      - "443"
    networks:
      - server
      - login
    ports:
      - "9200"
    links:
      - login-db
    restart: always
  dcc-dashboard:
    image: quay.io/ucsc_cgl/dashboard:1.0.9
    #build: dcc-dashboard
    ports:
      - "80"
      - "443"
    volumes:
      - ~/dcc-dashboard/logs:/app/log
#      - dashboard1:/app
    environment:
      GOOGLE_CLIENT_ID: "${google_client_id}"
      GOOGLE_CLIENT_SECRET: "${google_client_secret}"
      DCC_DASHBOARD_HOST: "${dcc_dashboard_host}"
      DCC_DASHBOARD_PROTOCOL: "${dcc_dashboard_protocol}"
      DCC_DASHBOARD_SERVICE: "${dcc_dashboard_service}"
      DCC_INVOICING_SERVICE: "${dcc_invoicing_service}"
      DCC_ACTION_SERVICE: "${dcc_action_service}"
      L_POSTGRES_USER: "${login_user}"
      L_POSTGRES_PASSWORD: "${login_password}"
      L_POSTGRES_DB: "${login_db}"
      SECRET_KEY: "${secret_key}"
      LOG_IN_TOKEN: "${login_token}"
      SERVER_NAME: "${dcc_dashboard_host}"
      DCC_CORE_CLIENT_VERSION: "${core_client_version}"
      ES_SERVICE: "${es_service}"
      BD_POSTGRES_USER: "${login_user}"
      BD_POSTGRES_PASSWORD: "${login_password}"
      BD_POSTGRES_DB: "burndown"
    networks:
      - server
      - login
      - bd
    links:
      - login-db
    restart: always
  nginx:
    build: nginx-image
    links:
      - dcc-dashboard
      - dcc-dashboard-service
    environment:
      - VIRTUAL_HOST=${dcc_dashboard_host}
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=redirect
      - LETSENCRYPT_HOST=${dcc_dashboard_host}
      - LETSENCRYPT_EMAIL="default@email.com"
    mem_limit: 2g
    cpu_shares: 256
    ports:
      - "80"
      - "443"
    networks:
      - core_public
      - server
    restart: always
  boardwalk:
    image: quay.io/ucsc_cgl/boardwalk:1.0.0
    environment:
      - BOARDWALK_HOST=${dcc_dashboard_host}
    networks:
      - server
    ports:
      - "80"
      - "443"
      - "3000"
    volumes:
      - boardwalk1:/usr/src/app
    restart: always
  login-db:
    image: postgres:9.6-alpine
    container_name: "login-db"
    environment:
      POSTGRES_PASSWORD: "${login_password}"
      POSTGRES_USER: "${login_user}"
      POSTGRES_DB: "${login_db}"
    volumes:
      - login_postgres:/var/lib/postgresql/data
    networks:
      - login
    restart: always

volumes:
  postgres:
    driver: local
  billing_postgres:
    driver: local
  login_postgres:
    driver: local
  dashboard1:
    driver: local
  boardwalk1:
    driver: local
networks:
  core_public:
    external: true
  server:
    driver: bridge
  login:
    driver: bridge
